// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Nv7AdojRIZkM_8Siz9m0CCg29g-_fFQ',
    appId: '1:1096303081679:web:9b25b5945117e2b9be1fba',
    messagingSenderId: '1096303081679',
    projectId: 'auth-firebse-project-2026',
    authDomain: 'auth-firebse-project-2026.firebaseapp.com',
    storageBucket: 'auth-firebse-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNimwqeg8Wq6jDOSHocEzb0I2VmOvfX78',
    appId: '1:1096303081679:android:16307af80d9644c7be1fba',
    messagingSenderId: '1096303081679',
    projectId: 'auth-firebse-project-2026',
    storageBucket: 'auth-firebse-project-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLexgVeXga2Lm5pjSiscbR_Q8RV99AKN4',
    appId: '1:1096303081679:ios:4b43fcf8473d1181be1fba',
    messagingSenderId: '1096303081679',
    projectId: 'auth-firebse-project-2026',
    storageBucket: 'auth-firebse-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.authFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLexgVeXga2Lm5pjSiscbR_Q8RV99AKN4',
    appId: '1:1096303081679:ios:4b43fcf8473d1181be1fba',
    messagingSenderId: '1096303081679',
    projectId: 'auth-firebse-project-2026',
    storageBucket: 'auth-firebse-project-2026.firebasestorage.app',
    iosBundleId: 'com.example.authFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Nv7AdojRIZkM_8Siz9m0CCg29g-_fFQ',
    appId: '1:1096303081679:web:206aefc84683c315be1fba',
    messagingSenderId: '1096303081679',
    projectId: 'auth-firebse-project-2026',
    authDomain: 'auth-firebse-project-2026.firebaseapp.com',
    storageBucket: 'auth-firebse-project-2026.firebasestorage.app',
  );
}
